sudo: false
language: node_js

node_js:
  - "8"
  - "9"
  - "10"
  - "11"
  - "12"

os:
  - linux

install:
  - npm install
  - npm i -g typescript jest

script: npm run test

branches:
  only:
    - master